### ISSUE TITLE
Crashes and burns with XCode 6.3

### ISSUE THREAD

**Issue by kootsoop** [PaulSolt/CustomViewFromXib#1]
Just read through the blog post (nice!) and downloaded the code... and it dies pretty comprehensively for me.

Any pointers?

![screen shot 2015-04-20 at 3 42 49 pm](https://cloud.githubusercontent.com/assets/82619/7238936/135b861e-e774-11e4-9a27-79ff05a0a217.png)

**Comment by PaulSolt** [comment]
I don't have this issue with Xcode 6.3

Clean and rebuild?

I'd recommend my newest post on IBDesignables: http://iphonedev.tv/blog/2014/12/15/create-an-ibdesignable-uiview-subclass-with-code-from-an-xib-file-in-xcode-6
